export const LOGIN_REQUEST_STARTED = 'auth/LOGIN_REQUEST_STARTED'
export const LOGIN_REQUEST_SUCCEEDED = 'auth/LOGIN_REQUEST_SUCCEEDED'
export const LOGIN_ERROR_SUCCEEDED = 'auth/LOGIN_ERROR_SUCCEEDED'
export const LOGOUT_SUCCEEDED = 'auth/LOGOUT_SUCCEEDED'
