export const ADD_TASK = 'task-list/ADD_TASK'
export const CHANGE_NEW_TASK_NAME= 'task-list/CHANGE_NEW_TASK_NAME'
export const CHANGE_NEW_TASK_CATEGORY = 'task-list/CHANGE_NEW_TASK_CATEGORY'
export const DELETE_TASK = 'task-list/DELETE_TASK'
export const COMPLETE_TASK = 'task-list/COMPLETE_TASK'
